<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OrchardCoreProjectType>None</OrchardCoreProjectType>
  </PropertyGroup>

  <Import Project="../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.Module.Targets/Lombiq.MSBuild.Module.Targets.props"
          Condition="'$(NuGetBuild)' != 'true' "/>

  <PropertyGroup>
    <Title>Lombiq Setup Extensions for Orchard Core</Title>
    <Copyright>Copyright © 2020, Lombiq Technologies Ltd.</Copyright>
    <Description>Lombiq Setup Extensions for Orchard Core: Extensions for setting up an Orchard Core application. See the project website for detailed documentation.</Description>
    <PackageTags>OrchardCore;Lombiq;AspNetCore;Setup</PackageTags>
    <RepositoryUrl>https://github.com/Lombiq/Setup-Extensions</RepositoryUrl>
    <PackageProjectUrl>https://github.com/Lombiq/Setup-Extensions</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OrchardCore.Abstractions" Version="$(OrchardCoreVersion)" />
    <PackageReference Include="OrchardCore.Infrastructure" Version="$(OrchardCoreVersion)" />
  </ItemGroup>

  <Import Project="../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.Module.Targets/Lombiq.MSBuild.Module.Targets.targets"
          Condition="'$(NuGetBuild)' != 'true' "/>

</Project>
